spring.application.name=ms-auth-service
spring.profiles.active=${APP_PROFILE:dev}

jwt.secret=${JWT_SECRET:QWxhZGRpbjpPcGVuU2VzYW1lU3VwZXJTZWd1cmUxMjM0NTY}

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.timeout=5000ms

