spring.application.name=ms-auth-service
spring.profiles.active=${APP_PROFILE:test}

# JWT
jwt.secret=${JWT_SECRET}

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Render
server.port=${PORT:8080}

# postgres
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
